Include all imports

In [55]:
import numpy as np
import numpy.linalg as lin
import pandas as pd
import os

Import all necessary matricies from csv files and convert them to np arrays 

In [98]:
A_df = pd.read_csv('A.csv',  header=None)
A = A_df.to_numpy()
#print(A)

R1_df = pd.read_csv('R1.csv',  header=None)
R1 = R1_df.to_numpy()
#print(R1)

b_df = pd.read_csv('b.csv',  header=None)
b = b_df.to_numpy()
#print(b)

Q_df = pd.read_csv('Q.csv',  header=None)
QT = Q_df.to_numpy().T
#print(QT)

b1 = np.dot(QT, b)[range(4)]
print(b1)

[[-1.31805775]
 [-0.18084474]
 [-0.20134004]
 [-0.53867162]]


Perform the computation of R_1 * x = b to solve for x using the linalg.solve function in np.
Also check results using lin.lstsq()

In [97]:
x = lin.solve(R1,b1)
x_1 = lin.lstsq(A, b, rcond=None)
print(x)
print(x_1)

[[ 0.15411017]
 [ 1.23326873]
 [ 0.87632533]
 [-1.15248528]]
(array([[ 0.15410623],
       [ 1.2332279 ],
       [ 0.87626071],
       [-1.15228633]]), array([0.00859745]), 4, array([2.78207711, 0.83463247, 0.57975785, 0.30184012]))


Note out final answer for matches our answer for x in part (a)

Question: 12

In [54]:
A = np.array([[1, 0], [2,  7], [3, 5]])
AT = A.T
#print(A)
#print(AT)
ATA = np.dot(AT, A)
print(ATA)

[[1 0]
 [2 7]
 [3 5]]
[[1 2 3]
 [0 7 5]]
[[14 29]
 [29 74]]


In [59]:
# Find eigenvalues and eigenvectors of ATA
print(ATA)
lamdas, eigVectors = lin.eig(ATA)
print(lamdas)
print(eigVectors)

[[14 29]
 [29 74]]
[ 2.27470791 85.72529209]
[[-0.92708909 -0.37484105]
 [ 0.37484105 -0.92708909]]


In [63]:
U, S, VT = lin.svd(A, full_matrices=False)
print(U)
print(S)
print(VT)

[[-0.04048486  0.61469355]
 [-0.78188419 -0.51034496]
 [-0.62210778  0.60141488]]
[9.25879539 1.50821348]
[[-0.37484105 -0.92708909]
 [ 0.92708909 -0.37484105]]


In [83]:
# Determine U: Av = (sigma)u
#AV = -np.dot(A, VT.T)
#print(AV)

#Sigma = np.array([[9.2588, 0],
#                 [0, 1.5082],

v1 = np.array([[0.3748], [0.9271]])
print(v1)
u1 = np.dot(A, v1) / 9.2588
print(u1)

v2 = np.array([[-0.9271], [0.3748]])
print(v2)
u2 = np.dot(A, v2) / 1.5082
print(u2)

U = [u1, u2]
print(U)


[[0.3748]
 [0.9271]]
[[0.04048041]
 [0.78188318]
 [0.62210006]]
[[-0.9271]
 [ 0.3748]]
[[-0.61470627]
 [ 0.51014454]
 [-0.60157804]]
[array([[0.04048041],
       [0.78188318],
       [0.62210006]]), array([[-0.61470627],
       [ 0.51014454],
       [-0.60157804]])]
